import type { Metadata } from "next";
import { Poppins, Pixelify_Sans } from "next/font/google";
import clsx from "clsx";

import "./globals.css";

const poppins = Poppins({
    variable: "--font-poppins",
    weight: ["400", "500", "600"],
});

const pixelifySans = Pixelify_Sans({
    variable: "--font-pixelify-sans",
    weight: ["400", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={clsx(poppins.variable, pixelifySans.variable, "antialiased")}>
                {children}
            </body>
        </html>
    );
}
