export const ENVS = Object.freeze({
    PUBLIC_ENVIRONMENT: import.meta.env.PUBLIC_ENVIRONMENT || "development",
    PUBLIC_SITE_URL: import.meta.env.PUBLIC_SITE_URL || "http://localhost:3000",
    SENTRY_AUTH_TOKEN: import.meta.env.SENTRY_AUTH_TOKEN || "",
    SENTRY_ORG: import.meta.env.SENTRY_ORG || "",
    SENTRY_PROJECT: import.meta.env.SENTRY_PROJECT || "",
    SENTRY_DSN: import.meta.env.SENTRY_DSN || "",
    SENTRY_RELEASE: import.meta.env.SENTRY_RELEASE || "",
    SENTRY_ENVIRONMENT:
        import.meta.env.SENTRY_ENVIRONMENT || import.meta.env.PUBLIC_ENVIRONMENT || "development",
    SENTRY_SAMPLE_RATE: import.meta.env.SENTRY_SAMPLE_RATE || "1.0",
    SENTRY_TRACES_SAMPLE_RATE: import.meta.env.SENTRY_TRACES_SAMPLE_RATE || "0.2",
    SENTRY_PROFILES_SAMPLE_RATE: import.meta.env.SENTRY_PROFILES_SAMPLE_RATE || "0.0",
    SENTRY_DEBUG: import.meta.env.SENTRY_DEBUG || "false",
    PUBLIC_SENTRY_ENABLED: import.meta.env.PUBLIC_SENTRY_ENABLED || "false",
    PUBLIC_GA_MEASUREMENT_ID: import.meta.env.PUBLIC_GA_MEASUREMENT_ID || "",
    PUBLIC_WEB3FORMS_ACCESS_KEY: import.meta.env.PUBLIC_WEB3FORMS_ACCESS_KEY || "",
    STRAPI_API_URL: import.meta.env.STRAPI_API_URL || "http://localhost:1337/api",
    STRAPI_API_TOKEN: import.meta.env.STRAPI_API_TOKEN || "",
    STRAPI_CMS_OPTIONAL: import.meta.env.STRAPI_CMS_OPTIONAL === "true",
});
