import "@/styles/globals.css";

import clsx from "clsx";
import type { Metadata } from "next";
import { Pixelify_Sans, Poppins } from "next/font/google";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";

import { routing } from "@/i18n/routing";
import Layout from "@/layouts/root-layout";

const poppins = Poppins({
    variable: "--font-poppins",
    weight: ["400", "500", "600"],
    subsets: ["latin"],
});

const pixelifySans = Pixelify_Sans({
    variable: "--font-pixelify-sans",
    weight: ["400", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface Props {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}

export default async function RootLayout({ children, params }: Readonly<Props>) {
    const { locale } = await params;

    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }

    return (
        <html lang={locale}>
            <body className={clsx(poppins.variable, pixelifySans.variable, "antialiased")}>
                <NextIntlClientProvider>
                    <Layout>{children}</Layout>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
